version: "3"

services:
  front-end:
    build: front-end/
    ports:
      - "8080:80"
    environment:
      - RABBITMQ_USER=${USER}
      - RABBITMQ_PASS=${PASS}
    # uncomment for development
    volumes:
      - "./front-end/app:/var/www/html"
  messaging:

  back-end:

#  db:	
