version: "3"

services:
#  front-end:
#    build: .
#    ports:
#      - "8080:80"
#    environment:
#      - RABBITMQ_USER=${USER}
#      - RABBITMQ_PASS=${PASS}
#    volumes:
#      - "./app:/var/www/html"
  messaging:
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
  back-end:
    build: back-end/
    environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
#  db:	
