version: "3"

services:
  front-end:

  messaging:
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
  back-end:
    build: back-end/
    environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
#  db:	
