version: '3'
services:
    # tag::messaging[]
    messaging:
        image: 'rabbitmq:3-management'
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        ports:
            - 15672:15672
    # end::messaging[]
    # tag::adminer[]
    adminer:
        image: 'adminer'
        ports:
            - 8080:8080
    # end::adminer[]
    # tag::db[]
    db:
        build: ./db
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - data-volume:/var/lib/postgresql/data
    # end::db[]
    # tag::front-end[]
    front-end:
        build: ./front-end
        ports:
            - 5000:5000
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            FLASK_ENV: development
            FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    # end::front-end[]
    # tag::back-end[]
    back-end:
        build: ./back-end
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # end::back-end[]
volumes:
    data-volume: