version: "3.0"
services:
    # tag::db_services[]
    db1:
        build: ./db
        environment:
            POSTGRES_PASSWORD: asdffdsa
            POSTGRES_REPLICA_PASSWORD: asdffdsa
            POSTGRES_NODES: "db1 db2"
    db2:
        build: ./db
        environment:
            POSTGRES_PASSWORD: asdffdsa
            POSTGRES_REPLICA_PASSWORD: asdffdsa
            POSTGRES_NODES: "db1 db2"
    # end::db_services[]
    adminer:
        image: adminer
        ports:
            - "8080:8080"